# Generated by Django 3.2.18 on 2023-02-25 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_author_user_ref'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='review',
            new_name='comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
